// src/mockData.js

export const mockProducts = [
  {
    _id: '681b4bf0d7dc28ce9fcb1a10',
    name: 'Wireless Headphones',
    description: 'High-quality wireless headphones with noise cancellation.',
    price: 199.99,
    image: 'https://via.placeholder.com/300x200?text=Wireless+Headphones',
    category: 'Electronics',
    rating: 4.5,
  },
  {
    _id: '2',
    name: 'Smart Watch',
    description: 'Smart watch with heart rate monitor and GPS.',
    price: 249.99,
    image: 'https://via.placeholder.com/300x200?text=Smart+Watch',
    category: 'Electronics',
    rating: 4.2,
  },
  {
    _id: '3',
    name: 'Running Shoes',
    description: 'Comfortable running shoes with excellent support.',
    price: 89.99,
    image: 'https://via.placeholder.com/300x200?text=Running+Shoes',
    category: 'Sports',
    rating: 4.7,
  },
   {
    _id: '1',
    name: 'Wireless Headphones',
    description: 'High-quality wireless headphones with noise cancellation.',
    price: 199.99,
    image: 'https://via.placeholder.com/300x200?text=Wireless+Headphones',
    category: 'Electronics',
    rating: 4.5,
  },
  {
    _id: '2',
    name: 'Smart Watch',
    description: 'Smart watch with heart rate monitor and GPS.',
    price: 249.99,
    image: 'https://via.placeholder.com/300x200?text=Smart+Watch',
    category: 'Electronics',
    rating: 4.2,
  },
  {
    _id: '3',
    name: 'Running Shoes',
    description: 'Comfortable running shoes with excellent support.',
    price: 89.99,
    image: 'https://via.placeholder.com/300x200?text=Running+Shoes',
    category: 'Sports',
    rating: 4.7,
  },
   {
    _id: '1',
    name: 'Wireless Headphones',
    description: 'High-quality wireless headphones with noise cancellation.',
    price: 199.99,
    image: 'https://via.placeholder.com/300x200?text=Wireless+Headphones',
    category: 'Electronics',
    rating: 4.5,
  },
  {
    _id: '2',
    name: 'Smart Watch',
    description: 'Smart watch with heart rate monitor and GPS.',
    price: 249.99,
    image: 'https://via.placeholder.com/300x200?text=Smart+Watch',
    category: 'Electronics',
    rating: 4.2,
  },
  {
    _id: '3',
    name: 'Running Shoes',
    description: 'Comfortable running shoes with excellent support.',
    price: 89.99,
    image: 'https://via.placeholder.com/300x200?text=Running+Shoes',
    category: 'Sports',
    rating: 4.7,
  },
];

export const mockComments = [
  {
    _id: '1',
    productId: '1',
    user: 'User1',
    text: 'Great headphones! The noise cancellation is amazing.',
    rating: 5,
  },
  {
    _id: '2',
    productId: '1681b4bf0d7dc28ce9fcb1a10',
    user: 'User2',
    text: 'Good quality, but a bit expensive.',
    rating: 4,
  },
  {
    _id: '3',
    productId: '2',
    user: 'User3',
    text: 'The smart watch is very accurate and has great features.',
    rating: 5,
  },
];
